version: '3.8'

services:
  n8n:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        N8N_VERSION: latest
    container_name: n8n-custom
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      # Basic configuration
      - N8N_BASIC_AUTH_ACTIVE=false
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production

      # Database configuration (uncomment to use PostgreSQL)
      # - DB_TYPE=postgresdb
      # - DB_POSTGRESDB_HOST=postgres
      # - DB_POSTGRESDB_PORT=5432
      # - DB_POSTGRESDB_DATABASE=n8n
      # - DB_POSTGRESDB_USER=n8n
      # - DB_POSTGRESDB_PASSWORD=n8n

      # Webhook URL (change to your domain)
      # - WEBHOOK_URL=https://your-domain.com/

      # Security (uncomment to enable basic auth)
      # - N8N_BASIC_AUTH_ACTIVE=true
      # - N8N_BASIC_AUTH_USER=admin
      # - N8N_BASIC_AUTH_PASSWORD=password
    volumes:
      # Persist n8n data
      - n8n_data:/home/node/.n8n

      # Optional: Mount custom nodes directory
      # - ./custom-nodes:/home/node/.n8n/custom

      # Optional: Mount custom configuration
      # - ./custom-config:/home/node/.n8n/config
    networks:
      - n8n-network
    depends_on:
      - postgres

  # Optional: PostgreSQL database
  postgres:
    image: postgres:15-alpine
    container_name: n8n-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=n8n
      - POSTGRES_USER=n8n
      - POSTGRES_PASSWORD=n8n
      - POSTGRES_NON_ROOT_USER=n8n
      - POSTGRES_NON_ROOT_PASSWORD=n8n
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - n8n-network
    # Uncomment to expose PostgreSQL port
    # ports:
    #   - "5432:5432"

volumes:
  n8n_data:
    driver: local
  postgres_data:
    driver: local

networks:
  n8n-network:
    driver: bridge
